apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  template:
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-frontend
spec:
  ports:
    - port: {{ .Values.frontend.servicePort }}
  selector:
    app: {{ include "my-app.fullname" . }}-frontend
  type: {{ .Values.frontend.serviceType }}
